# Generated by Django 6.0 on 2026-01-30 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_order_orderitem'),
        ('products', '0006_product_product_hash_product_tx_hash_and_more'),
    ]

    operations = [
    ]
