# Generated by Django 6.0 on 2026-01-22 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentproject',
            name='additional_docs',
            field=models.FileField(blank=True, null=True, upload_to='project_docs/'),
        ),
        migrations.AddField(
            model_name='investmentproject',
            name='business_plan',
            field=models.FileField(blank=True, null=True, upload_to='business_plans/'),
        ),
        migrations.AddField(
            model_name='investmentproject',
            name='farmer_experience',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='investmentproject',
            name='farmer_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='investmentproject',
            name='farmer_rating',
            field=models.DecimalField(decimal_places=2, default=4.5, max_digits=3),
        ),
        migrations.AddField(
            model_name='investmentproject',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='project_images/'),
        ),
        migrations.AlterField(
            model_name='investmentproject',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('active', 'Active'), ('funded', 'Funded'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
