# Generated by Django 6.0 on 2026-01-30 13:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IdeaLegacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('short_description', models.TextField()),
                ('full_description', models.TextField()),
                ('is_paid', models.BooleanField(default=False)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('document', models.FileField(blank=True, null=True, upload_to='ideas/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('embedding', models.JSONField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='investmentcategory',
            options={},
        ),
        migrations.AlterModelOptions(
            name='investmentproject',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='investmentproject',
            name='deadline',
        ),
        migrations.RemoveField(
            model_name='investmentproject',
            name='full_description',
        ),
        migrations.RemoveField(
            model_name='investmentproject',
            name='minimum_investment',
        ),
        migrations.RemoveField(
            model_name='investmentproject',
            name='short_description',
        ),
        migrations.AddField(
            model_name='investment',
            name='investment_structure',
            field=models.CharField(choices=[('fixed', 'Fixed Amount'), ('units', 'Share/Unit Based')], default='fixed', max_length=20),
        ),
        migrations.AddField(
            model_name='investment',
            name='investment_type',
            field=models.CharField(choices=[('fixed_amount', 'Fixed Amount'), ('unit_purchase', 'Share/Unit Purchase')], default='fixed_amount', max_length=20),
        ),
        migrations.AddField(
            model_name='investment',
            name='ownership_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='investment',
            name='total_units',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investment',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='investment',
            name='units',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investmentproject',
            name='additional_docs',
            field=models.FileField(blank=True, null=True, upload_to='additional_docs/'),
        ),
        migrations.AddField(
            model_name='investmentproject',
            name='available_units',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='investmentproject',
            name='business_plan',
            field=models.FileField(blank=True, null=True, upload_to='business_plans/'),
        ),
        migrations.AddField(
            model_name='investmentproject',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='investmentproject',
            name='farmer_experience',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='investmentproject',
            name='farmer_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='investmentproject',
            name='farmer_rating',
            field=models.DecimalField(decimal_places=2, default=4.5, max_digits=3),
        ),
        migrations.AddField(
            model_name='investmentproject',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='project_images/'),
        ),
        migrations.AddField(
            model_name='investmentproject',
            name='investment_structure',
            field=models.CharField(choices=[('fixed', 'Fixed Amount'), ('units', 'Share/Unit Based')], default='fixed', max_length=20),
        ),
        migrations.AddField(
            model_name='investmentproject',
            name='total_units',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='investmentproject',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='investment',
            name='payment_method',
            field=models.CharField(choices=[('payhere', 'PayHere'), ('stripe', 'Stripe/Card'), ('bank', 'Bank Transfer')], default='payhere', max_length=20),
        ),
        migrations.AlterField(
            model_name='investmentproject',
            name='investment_type',
            field=models.CharField(choices=[('equity', 'Equity Investment'), ('loan', 'Loan')], default='equity', max_length=10),
        ),
        migrations.AlterField(
            model_name='investmentproject',
            name='risk_level',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10),
        ),
        migrations.AlterField(
            model_name='investmentproject',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('active', 'Active'), ('funded', 'Funded'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='investmentproject',
            name='tags',
            field=models.TextField(blank=True, default='', help_text='Comma-separated tags'),
        ),
        migrations.AddConstraint(
            model_name='similarityalert',
            constraint=models.UniqueConstraint(fields=('idea', 'similar_idea'), name='unique_similarity_alert'),
        ),
        migrations.AddField(
            model_name='idealegacy',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ideas_legacy', to=settings.AUTH_USER_MODEL),
        ),
    ]
