# Generated by Django 6.0 on 2025-12-29 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('stock', models.CharField(choices=[('In Stock', 'In Stock'), ('Low Stock', 'Low Stock'), ('Out of Stock', 'Out of Stock')], max_length=20)),
                ('description', models.TextField()),
                ('reviews', models.PositiveIntegerField(default=0)),
                ('category', models.CharField(choices=[('oil', 'Coconut Oil'), ('fiber', 'Coir Fiber'), ('water', 'Coconut Water')], max_length=20)),
                ('type', models.CharField(choices=[('Raw Materials', 'Raw Materials'), ('Processed Goods', 'Processed Goods'), ('Equipment', 'Equipment')], max_length=30)),
            ],
        ),
    ]
