# Generated by Django 6.0 on 2026-01-01 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0002_remove_profile_role_remove_profile_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='investment',
            name='payment_status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='investment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
