# Generated by Django 6.0 on 2025-12-31 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0002_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='news/'),
        ),
    ]
