# Generated by Django 6.0 on 2025-12-31 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0003_news_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
