# Generated by Django 6.0 on 2026-01-01 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0003_investment_notes_investment_payment_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='investment',
            options={},
        ),
    ]
