# Generated by Django 6.0 on 2025-12-30 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0004_idea_attachment_alter_idea_author_ideapurchase'),
    ]

    operations = [
        migrations.RenameField(
            model_name='idea',
            old_name='attachment',
            new_name='file',
        ),
    ]
