# Generated by Django 6.0 on 2026-01-17 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0002_product'),
        ('connect', '0004_alter_investment_options'),
    ]

    operations = [
    ]
