# Generated by Django 6.0 on 2026-01-01 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0005_idea_document_alter_profile_role_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idea',
            name='document',
        ),
        migrations.AddField(
            model_name='idea',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='ideas/'),
        ),
        migrations.DeleteModel(
            name='Purchase',
        ),
    ]
