# Generated by Django 6.0 on 2026-01-01 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0006_remove_idea_document_idea_file_delete_purchase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idea',
            name='file',
        ),
        migrations.AddField(
            model_name='idea',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='idea_docs/'),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
