# Generated by Django 6.0 on 2026-01-01 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0007_remove_idea_file_idea_document_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='ideas/'),
        ),
    ]
