# Generated by Django 6.0 on 2026-01-01 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0008_alter_idea_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='short_description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='idea',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
