# Generated by Django 6.0 on 2026-01-01 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0009_alter_idea_short_description_alter_idea_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='short_description',
            field=models.TextField(),
        ),
    ]
