# Generated by Django 6.0 on 2026-01-07 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0010_alter_idea_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='embedding',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
