# Generated by Django 6.0 on 2026-01-07 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0011_idea_embedding'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='idea',
            options={'ordering': ['-created_at']},
        ),
    ]
