# Generated by Django 6.0 on 2026-01-17 10:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0012_alter_idea_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('stock', models.CharField(choices=[('In Stock', 'In Stock'), ('Low Stock', 'Low Stock'), ('Out of Stock', 'Out of Stock')], max_length=20)),
                ('description', models.TextField()),
                ('reviews', models.PositiveIntegerField(default=0)),
                ('category', models.CharField(choices=[('oil', 'Coconut Oil'), ('fiber', 'Coir Fiber'), ('water', 'Coconut Water')], max_length=20)),
                ('type', models.CharField(choices=[('Raw Materials', 'Raw Materials'), ('Processed Goods', 'Processed Goods'), ('Equipment', 'Equipment')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('farmer', 'Farmer'), ('investor', 'Investor'), ('buyer', 'Buyer'), ('admin', 'Admin')], default='buyer', max_length=20)),
                ('address', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
