# Generated by Django 6.0 on 2026-01-09 12:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0012_alter_idea_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SimilarityAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity_score', models.FloatField(default=0)),
                ('is_reported', models.BooleanField(default=False)),
                ('report_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('original_idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts_as_original', to='connect.idea')),
                ('original_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similarity_alerts', to=settings.AUTH_USER_MODEL)),
                ('similar_idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts_as_similar', to='connect.idea')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
