# Generated by Django 6.0 on 2026-01-21 14:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0013_product_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SimilarityAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity_score', models.FloatField()),
                ('is_reported', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('idea', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='connect.idea')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similarity_alerts', to=settings.AUTH_USER_MODEL)),
                ('similar_idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similar_to', to='connect.idea')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
