# Generated by Django 6.0 on 2026-01-19 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0004_news_likes'),
        ('connect', '0013_product_profile'),
    ]

    operations = [
    ]
