# Generated by Django 6.0 on 2026-01-22 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0014_similarityalert'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='similarityalert',
            name='owner',
        ),
        migrations.AddField(
            model_name='similarityalert',
            name='is_dismissed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='similarityalert',
            name='idea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similarity_alerts', to='connect.idea'),
        ),
        migrations.AlterField(
            model_name='similarityalert',
            name='similar_idea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triggered_alerts', to='connect.idea'),
        ),
        migrations.AddConstraint(
            model_name='similarityalert',
            constraint=models.UniqueConstraint(fields=('idea', 'similar_idea'), name='unique_similarity_alert'),
        ),
    ]
