# Generated by Django 6.0 on 2026-01-21 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0002_product'),
        ('connect', '0014_merge_0004_news_likes_0013_product_profile'),
    ]

    operations = [
    ]
