# Generated by Django 6.0 on 2026-01-23 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0015_merge_20260121_1653'),
        ('connect', '0015_remove_similarityalert_owner_and_more'),
    ]

    operations = [
    ]
