# Generated by Django 6.0 on 2026-01-31 12:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0004_repair_investment_units_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]


    operations = [
        migrations.CreateModel(
            name='AuthLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, default='', help_text='Role at time of event (e.g., admin/farmer/customer).', max_length=30)),
                ('action', models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout')], max_length=10)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed')], max_length=10)),
                ('message', models.CharField(blank=True, default='', help_text="Optional short note (e.g., 'Invalid credentials').", max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, help_text='User related to the auth event (can be null if user not found).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auth_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='connect_aut_created_7863df_idx'), models.Index(fields=['action', 'status'], name='connect_aut_action_ce04f1_idx'), models.Index(fields=['role'], name='connect_aut_role_c44968_idx')],
            },
        ),
    ]
