# Generated by Django 6.0 on 2026-01-31 12:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0018_authlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='authlog',
            name='connect_aut_role_c44968_idx',
        ),
        migrations.AlterField(
            model_name='authlog',
            name='message',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='authlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auth_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='authlog',
            name='role',
        ),
    ]
