# Generated by Django 6.0 on 2026-02-01 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0019_remove_authlog_connect_aut_role_c44968_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investment',
            name='investment_structure',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='investment_type',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='ownership_percentage',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='total_units',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='unit_price',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='units',
        ),
        migrations.RemoveField(
            model_name='investmentproject',
            name='farmer_experience',
        ),
        migrations.RemoveField(
            model_name='investmentproject',
            name='farmer_name',
        ),
        migrations.RemoveField(
            model_name='investmentproject',
            name='farmer_rating',
        ),
    ]
