# Generated by Django 6.0 on 2026-02-01 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0020_remove_investment_investment_structure_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='investment_structure',
            field=models.CharField(choices=[('fixed', 'Fixed Amount'), ('units', 'Share / Unit Based')], default='fixed', max_length=20),
        ),
        migrations.AddField(
            model_name='investment',
            name='investment_type',
            field=models.CharField(choices=[('fixed_amount', 'Fixed Amount'), ('unit_purchase', 'Share / Unit Purchase')], default='fixed_amount', max_length=20),
        ),
        migrations.AddField(
            model_name='investment',
            name='ownership_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='investment',
            name='total_units',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investment',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='investment',
            name='units',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
