# Generated by Django 6.0 on 2026-02-01 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0022_projectdraft_projectdraftmaterial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdraft',
            name='total_units',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
