# Generated by Django 6.0 on 2025-12-23 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentChainRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investment_id', models.IntegerField(unique=True)),
                ('tx_hash', models.CharField(max_length=66)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
